Added table column descriptions
documaster/noark5-web-services pull request #30
Opened 2020-02-06 10:24 UTC by rveda

Recieved questions about the table columns, so I added some descriptions.

2020-09-08 14:01 UTC, orlinDocumaster approved these changes

2021-11-04 08:57 UTC, teodoradobreva requested changes

2021-11-04 08:57 UTC, teodoradobreva commented on version1/02 - Object types.md
> +    - This field cannot be null. Ut must have a default value or a value provided via the api.
```suggestion
    - This field cannot be null. It must have a default value or a value provided via the API.
```

2021-11-05 09:00 UTC, ivaylomitrev commented
I've applied the change requested by @teodoradobreva and have no comments from myself

2021-11-05 09:03 UTC, teodoradobreva approved these changes

2021-11-05 09:04 UTC, ivaylomitrev approved these changes

2022-01-07 15:36 UTC, merged