Document the new endpoints for read/create/update of access groups
documaster/noark5-web-services pull request #47
Opened 2022-01-24 20:11 UTC by ivaylomitrev

This commit describes several new endpoints:
* GET/POST/PUT rms/api/public/noark5/v1/access-group/

2022-01-25 11:00 UTC, vulkodava requested changes

2022-01-25 11:00 UTC, vulkodava commented on version1/04 - Web services.md
> +            "id": integer,
Should this be long as per PR #45?

2022-01-25 11:00 UTC, vulkodava commented on version1/04 - Web services.md
> +    "id": integer,
Probably the type here must be long instead.

2022-01-25 11:00 UTC, vulkodava commented on version1/04 - Web services.md
> +200 OK
Should the response be 201 Created?

2022-01-25 11:00 UTC, vulkodava commented on version1/04 - Web services.md
> +    "id": integer,
Here type too.

2022-01-25 11:00 UTC, vulkodava commented on version1/04 - Web services.md
> +    "id": integer,
Type.

2022-01-25 13:29 UTC, ivaylomitrev commented on version1/04 - Web services.md
> +            "id": integer,
Fixed with https://github.com/documaster/noark5-web-services/pull/47/commits/0bc6296e6cdab8f679ef5bf3a2e5c1b519134158.

2022-01-25 13:29 UTC, ivaylomitrev commented on version1/04 - Web services.md
> +    "id": integer,
Fixed with https://github.com/documaster/noark5-web-services/pull/47/commits/0bc6296e6cdab8f679ef5bf3a2e5c1b519134158.

2022-01-25 13:29 UTC, ivaylomitrev commented on version1/04 - Web services.md
> +    "id": integer,
Fixed with https://github.com/documaster/noark5-web-services/pull/47/commits/0bc6296e6cdab8f679ef5bf3a2e5c1b519134158.

2022-01-25 13:29 UTC, ivaylomitrev commented on version1/04 - Web services.md
> +    "id": integer,
Fixed with https://github.com/documaster/noark5-web-services/pull/47/commits/0bc6296e6cdab8f679ef5bf3a2e5c1b519134158.

I like how each subsequent comment became shorter and shorter :D

2022-01-25 13:29 UTC, ivaylomitrev commented on version1/04 - Web services.md
> +200 OK
Fixed with https://github.com/documaster/noark5-web-services/pull/47/commits/f426db2322c123f1e647f27a0093544d62c5e9bc.

2022-01-25 13:30 UTC, ivaylomitrev commented
Comments thus far have been addressed.

2022-01-25 14:02 UTC, vulkodava approved these changes

2022-01-28 10:13 UTC, teodoradobreva approved these changes

2022-01-28 10:19 UTC, orlinDocumaster approved these changes

2022-01-28 14:38 UTC, plamenxpenchev requested changes

2022-01-28 14:38 UTC, plamenxpenchev commented on version1/04 - Web services.md
> +- **global permissions**
Inconsistent with the rest of the Details sections in the file. Should be globalPermissions across the endpoints. Similarly for service permissions.

2022-01-28 14:49 UTC, ivaylomitrev commented on version1/04 - Web services.md
> +- **global permissions**
Good point! Fixed with https://github.com/documaster/noark5-web-services/pull/47/commits/adf97e97f75ed8e10906c634b1eb9f26df452fb1.

2022-01-28 14:52 UTC, plamenxpenchev approved these changes

2022-01-28 14:53 UTC, teodoradobreva approved these changes

2022-01-31 11:33 UTC, ivaylomitrev commented
Squashed and rebased in preparation for merging.

2022-01-31 11:33 UTC, merged